version: "0.5"

log_level: info
log_location: devbox-services.log

processes:
  cassandra:
    command: "docker-compose -f $L1X_CFG_DC_FILE up cassandra1 cassandra2"
    is_daemon: true
    shutdown:
      command: "docker-compose -f $L1X_CFG_DC_FILE down cassandra1 cassandra2"
    readiness_probe:
      exec:
        command: "cqlsh -e 'SELECT * FROM system.local;' $L1X_CFG_CASSANDRA_HOST $L1X_CFG_CASSANDRA_PORT"
      initial_delay_seconds: 160
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 10
    availability:
      restart: "on_failure"
      backoff_seconds: 2

  l1x_node_server:
    command: "docker-compose -f $L1X_CFG_DC_FILE up l1x-node"
    is_daemon: true
    shutdown:
      command: "docker-compose -f $L1X_CFG_DC_FILE down  l1x-node"
    availability:
      restart: "on_failure"
      backoff_seconds: 5
    depends_on:
      cassandra:
        condition: process_healthy
